name: Deploy Investors Subdomain to Vercel

on:
  push:
    branches:
      - main
      - master
    paths:
      - "investors-subdomain/**"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "investors-subdomain/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./investors-subdomain
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_INVESTORS }}

      - name: Build Project Artifacts
        working-directory: ./investors-subdomain
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_INVESTORS }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./investors-subdomain
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_INVESTORS }}
